### ISSUE TITLE
Option to select default action

### ISSUE THREAD

**Issue by randywallace** [ANGkeith/telescope-terraform-doc.nvim#18]
This is really useful for our work in terraform!  We usually do our terraform work headless on the cloud and we can't perform X11Forward'ing of our SSH Sessions in order to perform the default open url action.  Would it be possible to add a config which supports having <CR> open in a split instead?  My muscle memory is quite atrophied in remembering that <c-d> opens docs in a split 🤣

**Comment by ANGkeith** [comment]
Hey @randywallace ,

Nice to know that this plugin is useful for you:). 


Thanks to @sbulav [here](https://github.com/ANGkeith/telescope-terraform-doc.nvim/pull/12), 

you should be able to `open docs in a split` with `<c-d>`

**Comment by randywallace** [comment]
Yeap!  That's what we use presently; I just can never remember the shortcut, lol

**Comment by ANGkeith** [comment]
I see... 

> I just can never remember the shortcut

By the way, for telescope, you can use `<C-/>` which will be helpful 
https://github.com/nvim-telescope/telescope.nvim/blame/master/README.md#L171-L174
![image](https://user-images.githubusercontent.com/28011783/208817210-054c1af4-2828-4cdd-b2c9-9c7f45449d30.png)



or you can always remap it to your mappings.
