### ISSUE TITLE
Error when executing

### ISSUE THREAD

**Issue by ElcomJ** [ANGkeith/telescope-terraform-doc.nvim#19]
Good morning.

I recently discovered your plugin and loved its functionality, but soon after installing and running it, it takes a while to run and then returns this `error`:

![Error](https://user-images.githubusercontent.com/37147897/211157018-f38112d6-6b61-4976-b047-6a37b88ee3a2.PNG)

I would like to know how I can solve it, or if it is a problem with the extension itself.

**Comment by ANGkeith** [comment]
Hi @ElcomJ , 

seemed like the version of `curl` that you are using does not support `--compressed`. 

Do you think it is possible to install a curl with the feature supported ? 
![image](https://user-images.githubusercontent.com/28011783/211250088-b17a14ef-d351-42a2-a147-a0d37fdaca85.png)

**Comment by ElcomJ** [comment]
Hello @ANGkeith , good morning.

I think it must be because I use `windows` as OS, and probably curl for windows doesn't have the same functions as on a Linux system, and that must be the problem.

But thanks for the help, I'm sure it must be because of that.

Have a nice day :)
