### ISSUE TITLE
Module documentation 

### ISSUE THREAD

**Issue by simonweil** [ANGkeith/telescope-terraform-doc.nvim#2]
Hi @ANGkeith

I installed your plugin yesterday and I really love it!

Any chance to add also modules with links to terraform site and directly to the github repo?

I usually dive into the implementation of modules on github to understand usage as I find the site not informative enough and lacking info when it comes to nested maps as variables

Thanks for the great extension to teleport

**Comment by ANGkeith** [comment]
hey @simonweil, np :)

you mean you want to be able to quickly open terraform modules github such as [this](https://github.com/terraform-aws-modules/terraform-aws-vpc)  ?

for that, i will actually recommend the [telescope bookmark](https://github.com/dhruvmanila/telescope-bookmarks.nvim) plugin.

**Comment by simonweil** [comment]
No, I mean an option to search for modules and once the module is found open either the terraform website of the module or the github repo.

Currently I search on Google or the terraform website and once I find the required module, I usually go to the github repo.

This option in the plugin could make this process much faster

Thanks for the quick response!

**Comment by ANGkeith** [comment]
ok, i will see what i can do, but will probably take some time to work on this feature

**Comment by simonweil** [comment]
No problem at all, thanks for the useful plugin

**Comment by ANGkeith** [comment]
sorry for the spam
