### ISSUE TITLE
Question: Mappings/Default action

### ISSUE THREAD

**Issue by verygitmuchhub** [ANGkeith/telescope-terraform-doc.nvim#31]
Hey guys,

related to #18. I have `<C-D>` configured in telescope for something completely different and I am having a hard time to understand how to configure this extension

- a) for different bindings
- b) even better to configure telescope default action (`<CR> `) to use the split window option

Is there any chance you can provide a snippet for a custom `url_open_handler` that opens the docs in the split window?, or anything similar? 
Default action, xdg-open (whatever), external software (browser) is not an option for me. `<C-D>` neither is.

Any hint **greatly** appreciated!, and, btw, thanks for such pieces of software to make peoples lifes so much better.

**Comment by verygitmuchhub** [comment]
To my suprise `<C-D>` works fine in the picker. Would be the question left whether it was possible to configure the default behaviour to use the split window.

**Comment by ANGkeith** [comment]
Hey, 
 
> whether it was possible to configure the default behaviour to use the split window.

Seemed like previously, it was'nt exactly that configurable. 

I have just made a small update, checkout https://github.com/ANGkeith/telescope-terraform-doc.nvim?tab=readme-ov-file#quirks

**Comment by verygitmuchhub** [comment]
Sorry, lost track of this one. Thank you for the update!
